---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
imageUrl: "https://raw.githubusercontent.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/master/logo.png"
version: "0.7.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Send newsletters for recently added media"
description: "This plugin automacially scans a users library (default every 4 hours), populates a list of recently added (not previously scanned) media, sends out the messages to configured clients(email, discord webhook)."
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Newsletters.dll"
  - "SQLitePCL.pretty.dll"
changelog: >
  - Discord webhook support.
  - Discord config addition in the plugin page.
  - Plugin page update.
  - Code refactoring to support future clients support.
  FULL CHANGELOG: https://raw.githubusercontent.com/Cloud9Developer/Jellyfin-Newsletter-Plugin/master/CHANGELOG.md
