---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
version: "0.5.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Send newsletters for recently added"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.Newsletters.dll"
changelog: >
  changelog
